### ISSUE TITLE
i cant download using my localhost url

### ISSUE THREAD

**Issue by kjtigue** [dropbox/dropbox-sdk-php#30]
http://localhost:8000/download/Dropbox/Fuse%20Storage/10603617_871026839586115_3054484848793125902_n.jpg

i have this link
i am using laravel 4 
i already created an app in dropbox api
problem is i cant download because of laravel routes 'http://localhost:8000/download/Dropbox'

**Comment by cakoose** [comment]
Are you using the Dropbox PHP SDK?  If so, what does your code look like?

How did you generate that link?
