### ISSUE TITLE
Download fopen Error

### ISSUE THREAD

**Issue by shidhu40** [dropbox/dropbox-sdk-php#34]
Hi,
I am using 
$client->getFile($content['path'],fopen($ftpdirectory.$newPath,'wb'))
function to download the file.
but it will produce this error:

failed to open stream: HTTP wrapper does not support writeable connections

But when I use local path it works properly.
So How can I move on different server path.

**Comment by cakoose** [comment]
What is the exact value of `$ftpdirectory.$newPath`?  The error message makes it seem like it's an HTTP URL, but the variable name makes it seem like it's an FTP URL.  If it's an HTTP URL, this site has something you can try: https://www.raditha.com/php/http/

Either way, this is not an issue with the Dropbox SDK.
