### ISSUE TITLE
hmac.new hexdigest PHP/Laravel equivalent

### ISSUE THREAD

**Issue by itsazzad** [dropbox/dropbox-sdk-php#36]
In the example python code signature is verifying like this:
`hmac.new(APP_SECRET, request.data, sha256).hexdigest()`

What will be the php equivalent?

I am using Laravel4.2:
```
list($appInfoJson, $appInfo) = dbx\AppInfo::loadFromJsonFileWithRaw($argAppInfoFile);
$data = \Request::all();
if($signature != hash_hmac('sha256', json_encode($data), $appInfoJson['secret'])){
    \App::abort(403);
}
```
What will be the `$data` Message to be hashed?

**Comment by cakoose** [comment]
What are you trying to do?  Where did you see the Python code?

**Comment by itsazzad** [comment]
@cakoose https://www.dropbox.com/developers/webhooks/tutorial here
```
    if signature != hmac.new(APP_SECRET, request.data, sha256).hexdigest():
```

**Comment by itsazzad** [comment]
I could solve that:
```
				$request_data = file_get_contents('php://input');
				if($signature != hash_hmac('sha256', $request_data, $appInfoJson['secret'])){
					\App::abort(403);
				}else{
				}
```

**Comment by motin** [comment]
> In the example python code signature is verifying like this:
> hmac.new(APP_SECRET, request.data, sha256).hexdigest()
> What will be the php equivalent?

It is `hash_hmac('SHA256', $message, $secret)` as demonstrated by this gist: https://gist.github.com/motin/7cbe1ae77bf493e3cae8

**Comment by richard457** [comment]
what is an output of $request_data in python or simply what message do we have to pass to get this hash?

**Comment by richard457** [comment]
I figured out the message could be something like $raw_data = file_get_contents('php://input') in laravel or simply make the request to be object not array.

**Comment by DemianD** [comment]
In Laravel:

```php
/**
 * @param Request $request
 *
 * @return bool
 */
public function verifySignature(Request $request): bool
{
    $signature = $request->header('X-Dropbox-Signature');
    $calculated = hash_hmac("sha256", $request->getContent(), config('services.dropbox.secret'));

    return hash_equals($signature, $calculated);
}
```
