### ISSUE TITLE
Wrong/case insensitive file name index, in delta call

### ISSUE THREAD

**Issue by itsazzad** [dropbox/dropbox-sdk-php#37]
Dropbox delta call is giving case insensitive file list in the index.
Actual name is: `'/CaSeSeNSiTivE/CaSeSeNSiTivE.docx'`
But showing as: `'/casesensitive/casesensitive.docx'`
```

    0 => 
    array (
      0 => '/casesensitive/casesensitive.docx',
      1 => 
      array (
        'rev' => '---',
        'thumb_exists' => false,
        'path' => '/CaSeSeNSiTivE/CaSeSeNSiTivE.docx',
        'is_dir' => false,
        'client_mtime' => 'Mon, 17 Aug 2015 12:54:14 +0000',
        'icon' => 'page_white_word',
        'bytes' => 4310,
        'modified' => 'Mon, 17 Aug 2015 14:37:52 +0000',
        'size' => '4.2 KB',
        'root' => 'app_folder',
        'mime_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'revision' => 618,
      ),
    ),
    1 => 
    array (
      0 => '/casesensitive/case sensitive.docx',
      1 => NULL,
    ),
```

![screenshot 2015-08-17 18 59 12](https://cloud.githubusercontent.com/assets/54909/9307457/7f01641a-4520-11e5-9105-98fff950777d.png)
![screenshot 2015-08-17 20 41 18](https://cloud.githubusercontent.com/assets/54909/9307456/7f012c3e-4520-11e5-9834-b4bbc1cf5b9c.png)
![screenshot 2015-08-17 20 41 30](https://cloud.githubusercontent.com/assets/54909/9307458/7f065aba-4520-11e5-86ae-5f885501fbec.png)

**Comment by smarx** [comment]
I believe everything here is in line with the expected behavior. See https://www.dropbox.com/developers/core/docs#delta.

**Comment by itsazzad** [comment]
@smarx 
This is how its coming after deleting the `'/CaSeSeNSiTivE/CaSe SeNSiTivE.docx'`,
![screenshot 2015-08-17 20 41 30](https://cloud.githubusercontent.com/assets/54909/9307458/7f065aba-4520-11e5-86ae-5f885501fbec.png)

Is it the expected behavior? If yes then how to know the actual file name which was just removed?

**Comment by smarx** [comment]
Yes, that's the expected behavior, per the documentation. Dropbox is
case-insensitive. There's no perfect way to know the current casing of the
file at the time of the delete, but you'll get 99%+ of the way there if you
just keep track of the path from the metadata when you last saw a change to
that file.

**Comment by itsazzad** [comment]
ok just got it that I have to fix it out by a case insensitive match:
```
Note: Dropbox treats file names in a case-insensitive but case-preserving way. To facilitate this, the <path> values above are lower-cased versions of the actual path. The last path component of the <metadata> value will be case-preserved.
```
