### ISSUE TITLE
[QUESTION] "New" 301 responses from getMetadata calls.

### ISSUE THREAD

**Issue by frankdejonge** [dropbox/dropbox-sdk-php#43]
In the last month I've received quite a number of errors with the Flysystem adapter for dropbox that all have to do with 301 responses and endpoint changes. Has something been changed there? I'm researching any regressions we may have introduced.

**Comment by greg-db** [comment]
Yes, the Dropbox API has begun redirecting with a 301 if you supply a double slash (e.g., "//" or something like "/%2F") in the URL. The redirect removes the extra path component. I can't promise if or when we'd be able to change that back, but the right way to make these calls is with a single slash anyway, so we recommend changing to doing it that way if possible.

**Comment by greg-db** [comment]
For reference, we've now reverted the behavior change, so the double slash version should work again. We do recommend only using a single slash though.

**Comment by frankdejonge** [comment]
@greg-db thanks for the response. I've corrected it on this end as well.
