### ISSUE TITLE
uploaded files Revision IDs are numeric values sometimes. 

### ISSUE THREAD

**Issue by Thamaraiselvam** [dropbox/dropbox-sdk-php#46]
We have noted revision IDs are string in mysql table rarely sometimes we get revision ids like 4e2137383789 so our code consider it as numeric value. I am not sure this is a bug . are you intentionally sending revision id like this?

we  are running on backup solution (taking backup using php code) so we need to to be sure whether it is string or numeric value.

**Comment by greg-db** [comment]
That is a valid rev value. These values should never be considered numbers (even if the string happens to only contain number characters), so you should make sure your code always handles these values as strings.
