### ISSUE TITLE
Does this library use Dropbox API v2?

### ISSUE THREAD

**Issue by fniephaus** [dropbox/dropbox-sdk-php#49]
Skimming over the code suggests otherwise. No mentioning of v2 at all.

Referring to [this blog post](https://blogs.dropbox.com/developers/2016/04/announcing-the-v1-to-v2-migration-guide/), there isn't a guideline for migrating to v2 in PHP yet.

**Comment by cakoose** [comment]
This SDK uses v1.

The end of the blog post says that migration instructions for PHP will be added before v1 is retired.

**Comment by fniephaus** [comment]
Thanks!

**Comment by jonrcable** [comment]
are there any plans to update this package to v2?

**Comment by greg-db** [comment]
No, unfortunately we don't currently have plans for an official PHP SDK for Dropbox API v2.

**Comment by fniephaus** [comment]
So how are we supposed to migrate to v2 then? Will Dropbox recommend a third party library instead?

**Comment by greg-db** [comment]
You can use the [HTTPS endpoints](https://www.dropbox.com/developers/documentation/http/documentation) directly or use a third party library. We can't officially endorse any third party libraries in particular, but we are listing them [here](https://www.dropbox.com/developers/documentation/communitysdks). There isn't currently one for PHP listed, but I am aware of [this one](https://github.com/Alorel/dropbox-v2-php).

**Comment by fniephaus** [comment]
Thanks, please keep us posted if possible!

**Comment by kunalvarma05** [comment]
@greg-db @fniephaus Mind giving [this](https://github.com/kunalvarma05/dropbox-php-sdk) a try? Actively working on it. Well [documented](https://github.com/kunalvarma05/dropbox-php-sdk/wiki/Getting-Started). Has [API Docs](https://kunalvarma05.github.io/dropbox-php-sdk).

**Comment by megaspy** [comment]
This is so disappointing... I have a lot of code with this library and using any different library means that I will have to change all the code...  
Maybe someone changed the v1 library ? Or does anyone know any solution with the same interface?

**Comment by minkbear** [comment]
got a reminder from dropbox

> On June 28, 2017, API v1 will be turned off. 
> 
> As a reminder, you need to sign in to the Dropbox developers site by September 28, 2016, and acknowledge that you’re aware of this change. 

ref: https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

**Comment by freekmurze** [comment]
I've created a PHP SDK that uses v2 of the API. 

https://github.com/spatie/dropbox-api

I'm accepting PRs that adds more endpoints to the package.

**Comment by donriga** [comment]
HTTP status 400 {"error": "v1_retired"}

**Comment by greg-db** [comment]
@donriga Per [the API v1 deprecation timeline](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/), API v1 has now been retired. This SDK does use API v1, so if you make any more API v1 calls with it, they will fail with that error. If you need more time to migrate your app to API v2, we can offer an extension for access to API v1. To request that, please [open an API ticket](https://www.dropbox.com/developers/contact) with the relevant app key(s).

We don't have plans for an official PHP SDK for Dropbox API v2, but you can use [a third party library](https://www.dropbox.com/developers/documentation/communitysdks), or you can call [the HTTPS endpoints](https://www.dropbox.com/developers/documentation/http/documentation) themselves.

**Comment by donriga** [comment]
I use another library for my problem
https://github.com/kunalvarma05/dropbox-php-sdk

**Comment by freekmurze** [comment]
Here's another one that works with v2 op the Dropbox API:
https://github.com/spatie/dropbox-api
