### ISSUE TITLE
Fatal error: Uncaught exception 'Dropbox\Exception_BadRequest' with message 'HTTP status 400 {"error_description": "redirect_uri mismatch", "error": "invalid_grant"}'

### ISSUE THREAD

**Issue by Thamaraiselvam** [dropbox/dropbox-sdk-php#50]
```
require_once "Dropbox/autoload.php";
use \Dropbox as dbx;
$appInfo = dbx\AppInfo::loadFromJsonFile("app-info.json");
$webAuth = new dbx\WebAuthNoRedirect($appInfo, "PHP-Example/1.0");

$authCode = $_REQUEST['code'];
list($accessToken, $dropboxUserId) = $webAuth->finish($authCode);
print "Access Token: " . $accessToken . "\n";
```

I used this code in my redirect URI page, i refered as per the doc , it throws following error.

`Fatal error: Uncaught exception 'Dropbox\Exception_BadRequest' with message 'HTTP status 400 {"error_description": "redirect_uri mismatch", "error": "invalid_grant"}' in /opt/lampp/htdocs/dropbox/lib/Dropbox/RequestUtil.php:250 Stack trace: #0 /opt/lampp/htdocs/dropbox/lib/Dropbox/WebAuthBase.php(43): Dropbox\RequestUtil::unexpectedStatus(Object(Dropbox\HttpResponse)) #1 /opt/lampp/htdocs/dropbox/lib/Dropbox/WebAuthNoRedirect.php(80): Dropbox\WebAuthBase->_finish('aS-XbXT8fbAAAAA...', NULL) #2 /opt/lampp/htdocs/dropbox/lib/index2.php(22): Dropbox\WebAuthNoRedirect->finish('aS-XbXT8fbAAAAA...') #3 {main} thrown in /opt/lampp/htdocs/dropbox/lib/Dropbox/RequestUtil.php on line 250`

i just went through to code and find following one,

`$webAuth->finish($authCode);`
Is calling following function in WebAuthNoRedirect.php
```
function finish($code)
    {
        Checker::argStringNonEmpty("code", $code);
        return $this->_finish($code, null);
    }
```

`_finish()` this function's 2nd param is null, but redirect URI should be here, when my replaced my redirect_uri as 2nd param instead of null like following.
`return $this->_finish($code, $my_redirect_uri);`

then it works fine, i got access token without any error.

**Comment by Thamaraiselvam** [comment]
Never mind , I was making wrong call. now it is working fine, i close this issue now.

**Comment by cakoose** [comment]
Glad you were able to resolve the issue.

To make sure your auth code is robust, try and follow the example code we've provided.  It demonstrates how to handle all the corner cases.
- [Example code from API docs](http://dropbox.github.io/dropbox-sdk-php/api-docs/v1.1.x/class-Dropbox.WebAuth.html)
- [web-file-browser example](https://github.com/dropbox/dropbox-sdk-php/blob/master/examples/web-file-browser.php)

**Comment by arradijamal** [comment]
what is the solution? I have the same problem.

**Comment by cakoose** [comment]
@arradijamal: Do not use this SDK.  It only works with the Dropbox API v1, which has been deprecated.

Look here for SDKs that work with the Dropbox API v2: https://www.dropbox.com/developers/documentation/communitysdks

As for the original question, I think maybe they were using `WebAuthNoRedirect` instead of `WebAuth`.
