### ISSUE TITLE
Downloading file returns /tmp/php2k8fjX

### ISSUE THREAD

**Issue by BenasPaulikas** [dropbox/dropbox-sdk-php#52]
Inside the file in which content should be saved /tmp/php2k8fjX is saved inside..

**Comment by greg-db** [comment]
@BenasPaulikas I'm not sure I understand your post. Can you share the code and steps to reproduce the issue, along with both the expected and actual results? Thanks in advance!

**Comment by BenasPaulikas** [comment]
Yii::$app->dropboxFs->has($fn) <- this one returns some good data like file name, type, size e.t.c.
$file = Yii::$app->dropboxFs->readStream($fn) <- this one returns string like /tmp/phpXYZXYZ
and the other one saves that string to file. So instead of downloading file from dropbox it saves some random string pointing to /tmp

**Comment by greg-db** [comment]
@BenasPaulikas It looks like you're using the [yii2-flysystem](https://github.com/creocoder/yii2-flysystem) library. That's a different project, and made by a third party, so I'm afraid I can't offer any insight on it. You may want to open an issue there.

**Comment by BenasPaulikas** [comment]
Sorry for that, but after downloading pure dropbox-sdk-php library it's all the same... I can get file info without problems but downloading file returns that string...

**Comment by greg-db** [comment]
@BenasPaulikas Can you share your code using dropbox-sdk-php that's giving you trouble?

**Comment by BenasPaulikas** [comment]
$a = "XYZLOOOOONG";
			$b = "SHORT";
			$client = new dbx\Client($a, $b);
			$metadata = $client->getFile($fn, fopen('/testfile.out', "wb"));
			if ($metadata === null) {
				fwrite(STDERR, "File not found on Dropbox.\n");
				die;
			}

$metadata has file info array and that testfile has string "/tmp/xadasdasd" inside..

**Comment by cakoose** [comment]
The return value from `getFile` doesn't contain the file contents -- just the metadata.  The file's contents are copied to whatever resource you provide as the second argument to `getFile`.

In this case, you provided "/testfile.out", so the file contents will be copied there.  To read load that file into a string, you can use a built-in PHP function:

```
$contents = file_get_contents("/testfile.out")
```

**Comment by BenasPaulikas** [comment]
That's the thing! $contents contain a "/tmp/XYZXYZ"

**Comment by greg-db** [comment]
@BenasPaulikas Is it possible that the file that you're downloading from Dropbox (at path `$fn` in your sample code) does actually contain that string? You can try downloading it from dropbox.com manually and checking that way.

**Comment by BenasPaulikas** [comment]
No. It's not possible. $metadata is not null it has info like file size, type e.t.c.

**Comment by cakoose** [comment]
What is the value of `$metadata`?

**Comment by BenasPaulikas** [comment]
array (size=12)
  'rev' => string '174b44fece' (length=10)
  'thumb_exists' => boolean false
  'path' => string '/documents/customer_31/index _28_.pdf' (length=37)
  'is_dir' => boolean false
  'client_mtime' => string 'Thu, 21 Jul 2016 12:21:35 +0000' (length=31)
  'icon' => string 'page_white_acrobat' (length=18)
  'bytes' => int 14
  'modified' => string 'Thu, 21 Jul 2016 12:21:35 +0000' (length=31)
  'size' => string '14 bytes' (length=8)
  'root' => string 'app_folder' (length=10)
  'mime_type' => string 'application/pdf' (length=15)
  'revision' => int 23

**Comment by greg-db** [comment]
The metadata indicates that the file has a length of 14, which is the length of the string "/tmp/php2k8fjX", so the file in your Dropbox "documents/customer_31/index 28.pdf", inside the app folder, does just contain that string. (It sounds like you accidentally uploaded that string, instead of uploading the file content from that path, at some point while developing your app. You can verify this by downloading the file from dropbox.com and opening it in a text editor.)
