### ISSUE TITLE
Make compatible with PHP 5.5.9

### ISSUE THREAD

**Issue by ReekenX** [dropbox/dropbox-sdk-php#53]
On Ubuntu shipped version with PHP 5.5.9 I receive following error:

    $ php -l vendors/dropbox-sdk-php-1.1.6/lib/Dropbox/Util.php
    PHP Parse error:  syntax error, unexpected '[' in vendors/dropbox-sdk-php-1.1.6/lib/Dropbox/Util.php on line 27
    Errors parsing vendors/dropbox-sdk-php-1.1.6/lib/Dropbox/Util.php

    $ php -v
    PHP 5.5.9-1ubuntu4.19 (cli) (built: Jul 28 2016 19:31:33) 
    Copyright (c) 1997-2014 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
        with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies$ php -v

Tested with 5.6.22 and PHP 7.0.9 - all works.

Older SDK version 1.1.5 works fine with PHP 5.5.9.

It's mistake in PHP support in Util library or my side?

**Comment by GrahamCampbell** [comment]
This library claims to work on PHP 5.3 upwards. Looks like a bug.

**Comment by GrahamCampbell** [comment]
https://github.com/dropbox/dropbox-sdk-php/pull/54

**Comment by cakoose** [comment]
Fixed in https://github.com/dropbox/dropbox-sdk-php/commit/d343a699d734837340f785589751ecbece3ef8f4
