### ISSUE TITLE
GetMetadatawithchildren

### ISSUE THREAD

**Issue by AbrarComDev** [dropbox/dropbox-sdk-php#55]
Hi,
 
I use dropbox-sdk-php-1.1.6 when i launch this 
print_r($client->getMetadataWithChildren("/"));
the result is only one folder not all children folders under /
 
Would you mind to bring me near for recursive listing of all children metadata under this dropbox sdk, or there is an other issue?
 
All my thanks,

**Comment by cakoose** [comment]
With this SDK (which supports Dropbox API v1), use [`getDelta()`](http://dropbox.github.io/dropbox-sdk-php/api-docs/v1.1.x/class-Dropbox.Client.html#_getDelta).

There are other SDKs that support Dropbox API v2 ([Alorel](https://github.com/Alorel/dropbox-v2-php), [kunalvarma05](https://github.com/kunalvarma05/dropbox-php-sdk)).  For those SDKs, call [`files/list_folder`](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder) with `recursive=true`.

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/t5/API-support/GetMetadatawithchildren-DROPBOX-PHP-SDK/m-p/190940 ]
