### ISSUE TITLE
how to get the dropbox file path 

### ISSUE THREAD

**Issue by owaisjamal** [dropbox/dropbox-sdk-php#56]
I need to upload a file and then get the path of the file from the dropbox and create a direct link to the file in the dropbox folder. Suggest any possible solution.

**Comment by greg-db** [comment]
Using this SDK, you can upload a file using [`uploadFile`](https://dropbox.github.io/dropbox-sdk-php/api-docs/v1.1.x/class-Dropbox.Client.html#_uploadFile). That will return the metadata for the uploaded file, including the path. Then, you can use [`createTemporaryDirectLink`](https://dropbox.github.io/dropbox-sdk-php/api-docs/v1.1.x/class-Dropbox.Client.html#_createTemporaryDirectLink) to get a temporary direct link to it.

Note that this library uses API v1 though, which is [deprecated](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/). You should switch to [API v2](https://www.dropbox.com/developers) whenever possible. There are some libraries for using API v2 from PHP listed on the [Community SDKs](https://www.dropbox.com/developers/documentation/communitysdks) page.

For reference, the equivalent endpoints for these operations on API v2 are [/2/files/upload](https://www.dropbox.com/developers/documentation/http/documentation#files-upload) and [/2/files/get_temporary_link](https://www.dropbox.com/developers/documentation/http/documentation#files-get_temporary_link).
