### ISSUE TITLE
Error: The PHP 64-bit integers

### ISSUE THREAD

**Issue by FamryAmri** [dropbox/dropbox-sdk-php#60]
Fatal error: Uncaught Exception: The Dropbox SDK uses 64-bit integers, but it looks like we're running on a version of PHP that doesn't support 64-bit integers (PHP_INT_MAX=2147483647).

this the problem then how to fix it
important: i'm newbie..

**Comment by cakoose** [comment]
This SDK is for V1 of the Dropbox API, which no longer works.

Here are some alternative SDKs you can try: https://www.dropbox.com/developers/documentation/communitysdks

**Comment by FamryAmri** [comment]
thanks
